apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-pong-y9rlrbgjw-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 3dd126c6-fef4-46ed-8a61-c5304e8a6f64
    macvlanNetName: mynad2
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    replicaCount: '1'
    service:
      type: NodePort
