apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-pong-y9rlrbgjw-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 880e06d8-3783-4296-a9ca-bb5ef1e6e261
    macvlanNetName: mynad2
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    replicaCount: '1'
    service:
      type: NodePort
