apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-ping-0mdqwuyi1-0-0-0
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 880e06d8-3783-4296-a9ca-bb5ef1e6e261
    macvlanNetName: mynad2
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/ping/metrics
        port: 18888
        scrape: true
      enabled: true
    replicaCount: '1'
    service:
      type: NodePort
