apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-ping-0mdqwuyi1-0-0-0
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 1cca1fba-d586-4b16-b660-334e6ed72153
    macvlanNetName: mynad3
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/ping/metrics
        port: 18888
        scrape: true
      enabled: true
    replicaCount: '1'
    service:
      type: NodePort
