apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-ping-0mdqwuyi1-0-0-0
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: dd7a9ad6-d6e0-4d88-afaa-4e756062f4df
    macvlanNetName: mynad3
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/ping/metrics
        port: 18888
        scrape: true
      enabled: true
    replicaCount: '1'
    service:
      type: NodePort
