apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-ping-0mdqwuyi1-0-0-0
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 7ac2a160-2247-4de7-a8a2-c6974a125a51
    macvlanNetName: mynad2
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/ping/metrics
        port: 18888
        scrape: true
      enabled: true
    replicaCount: '1'
    service:
      type: NodePort
