apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-46-pong-oqj4ikav6-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: dd7d2561-5fd8-4554-a976-0d7f798189c0
    macvlanNetName: mynad2
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    replicaCount: '1'
    service:
      type: NodePort
