apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-46-pong-oqj4ikav6-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 44b8343a-943a-428f-858c-5c628b311b27
    macvlanNetName: mynad2
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    replicaCount: '1'
    service:
      type: NodePort
