apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-46-pong-oqj4ikav6-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 7b281e0f-bc94-44f3-9fcc-a5a9c5903d8a
    macvlanNetName: mynad2
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    replicaCount: '1'
    service:
      type: NodePort
