apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-46-pong-oqj4ikav6-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: ec1693b4-4f17-4434-93eb-8172f06e28eb
    macvlanNetName: mynad2
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    replicaCount: '1'
    service:
      type: NodePort
