apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-co3-ping-iq9pfxq95-0-0-0
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 93553ab1-e93a-4ef9-a0f9-56b763a29ece
    macvlanNetName: mynad2
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/ping/metrics
        port: 18888
        scrape: true
      enabled: true
    replicaCount: '1'
    service:
      type: NodePort
