apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-ping-wnsx3yg3v-0-0-0
  namespace: default
spec:
  values:
    global:
      namespace: autobot-test25-pzk
      nsId: 2ca214ac-56ff-4812-ac64-5f93d7eb85e7
    macvlanNetName: defaultcombined1macvlanlinkprofile
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/ping/metrics
        port: 18888
        scrape: true
      enabled: true
    replicaCount: '1'
    service:
      type: NodePort
