apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-pong-ivj61fnzj-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: b2b1d0fb-c21d-4c3b-a0a0-d339636bbc9f
    macvlanNetName: defaultcombined1macvlanlinkprofile
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    replicaCount: '2'
    service:
      type: NodePort
