apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: he-4-pong-gacqpwhes-0-0-1
  namespace: default
spec:
  chart:
    spec:
      chart: ./fluxdc1/4/he-4-pong-gacqpwhes-0-0-1
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: fluxcdchartrepo3
        namespace: default
  interval: 5m0s
  postRenderers:
  - kustomize:
      patches:
      - patch: "\napiVersion: apps/v1\nkind: (Deployment|ReplicaSet|StatefulSet|DaemonSet)\n\
          metadata:\n  name: will-be-ingored\nspec:\n  template:\n    metadata:\n\
          \      annotations:\n        dzsi.com/dzsx-network-function-href: https://10.157.102.73:8008/tmf-api/mano/serviceInventory/v4/hello/service/service:DZSXNetworkFunction:hello:74cd5fbf-274f-4909-97c7-b3c6d039c4e1\n\
          \        dzsi.com/dzsx-network-function-id: service:DZSXNetworkFunction:hello:74cd5fbf-274f-4909-97c7-b3c6d039c4e1\n"
        target:
          kind: (Deployment|ReplicaSet|StatefulSet|DaemonSet)
  releaseName: he-4-pong-gacqpwhes-0-0-1
  targetNamespace: default
  values: {}
