apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-3-ping-f4ha158ho-0-0-0
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: ce2217bc-f75a-4c65-b621-cd7d6a67a180
    image:
      imagePullSecrets: []
      pullPolicy: IfNotPresent
      repository: artifactory.riftio.com/docker/rw.ping
      tag: '2004'
    macvlanNetName: mynad2
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/ping/metrics
        port: 18888
        scrape: true
      enabled: true
    replicaCount: 1
    service:
      type: NodePort
