apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-pong-5tbs4iwsl-0-0-2
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: caefafb3-62bc-4fc5-84b6-443fd347a992
    macvlanNetName: default-macvlan-net1
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    replicaCount: '1'
    service:
      type: NodePort
