apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-ping-tuee1ldvt-0-0-0
  namespace: default
spec:
  values:
    global:
      namespace: autobot-test25-pzk
      nsId: 44651f2f-b3ba-4564-bf98-0aecbb275b10
    macvlanNetName: defaultcombined3macvlanlinkprofile
    macvlanNetNamespace: default
    replicaCount: '2'
