apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-ping-tuee1ldvt-0-0-0
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 6f547427-f78f-445d-9a8b-ef32fb2b9e2a
    macvlanNetName: defaultcombined3macvlanlinkprofile
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/ping/metrics
        port: 18888
        scrape: true
      enabled: true
    replicaCount: '1'
    service:
      type: NodePort
