apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-ping-tuee1ldvt-0-0-0
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 8f2708c7-a774-4c7d-bc16-e75651a30e54
    macvlanNetName: defaultcombined3macvlanlinkprofile
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/ping/metrics
        port: 18888
        scrape: true
      enabled: true
    replicaCount: '1'
    service:
      type: NodePort
