apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-ping-tuee1ldvt-0-0-0
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 0213b1ed-4e14-4144-b9a4-0fc8e21fcbf8
    image:
      imagePullSecrets: []
      pullPolicy: IfNotPresent
      repository: rt.cloud.dzsi.local/docker/rw.ping
      tag: '2004'
    macvlanNetName: defaultcombined3macvlanlinkprofile
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/ping/metrics
        port: 18888
        scrape: true
      enabled: true
    replicaCount: 1
    service:
      type: NodePort
