apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-ping-tuee1ldvt-0-0-0
  namespace: default
spec:
  values:
    global:
      namespace: autobot-test25-pzk
      nsId: bbf4722f-f708-41e4-9377-a6a5fb8611b9
    macvlanNetName: defaultcombined3macvlanlinkprofile
    macvlanNetNamespace: default
    replicaCount: '2'
