apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-ping-tuee1ldvt-0-0-0
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 2b986b4e-a2fa-45f8-b1fe-06c26c032a0e
    macvlanNetName: defaultcombined3macvlanlinkprofile
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/ping/metrics
        port: 18888
        scrape: true
      enabled: true
    replicaCount: '1'
    service:
      type: NodePort
