apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-pong-ivj61fnzj-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 1f32c245-b55f-48b2-83bc-35c4628517c3
    macvlanNetName: mynad2
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    replicaCount: '1'
    service:
      type: NodePort
