apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-pong-ivj61fnzj-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 8f4b61b0-94c3-4f1c-b0ef-afbd2185ec6d
    macvlanNetName: mynad2
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    replicaCount: '1'
    service:
      type: NodePort
