apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-pong-yrkpvsna4-0-0-2
  namespace: default
spec:
  values:
    global:
      namespace: autobot-test25-pzk
      nsId: edef15ec-0002-4651-8756-004226a5e497
    macvlanNetName: default-macvlan-net1
    macvlanNetNamespace: defaultcombined7macvlanlinkprofile
    metrics:
      annotations:
        path: /api/v1/ping/metrics
        port: 18888
        scrape: true
      enabled: true
    replicaCount: '1'
    service:
      type: NodePort
