apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-46-ping-u4f8ubi1q-0-0-0
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 44b8343a-943a-428f-858c-5c628b311b27
    macvlanNetName: mynad2
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/ping/metrics
        port: 18888
        scrape: true
      enabled: true
    replicaCount: 2
    service:
      type: NodePort
