apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: he-4-ping-bujzguawj-0-0-0
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 6b5682eb-a9e9-4202-9f78-96598edd87fa
    image:
      imagePullSecrets: []
      pullPolicy: IfNotPresent
      repository: rt.cloud.dzsi.local/docker/rw.ping
      tag: '2004'
    macvlanNetName: mynad2
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/ping/metrics
        port: 18888
        scrape: true
      enabled: true
    replicaCount: 1
    service:
      type: NodePort
