apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-pong-lugfokuit-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: autobot-test25-pzk
      nsId: 67a339c2-10d1-45b1-9785-30a23c13f47b
    macvlanNetName: defaultcombined7macvlanlinkprofile
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/ping/metrics
        port: 18888
        scrape: true
      enabled: true
    replicaCount: '1'
    service:
      type: NodePort
