apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: he-32-pong-kmrbkaipk-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: f9e84d82-05b8-4d47-82e8-af8abc2c870e
    image:
      imagePullSecrets: []
      pullPolicy: IfNotPresent
      repository: rt.cloud.dzsi.local/docker/rw.pong
      tag: '2005'
    macvlanNetName: mynad2
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    service:
      type: NodePort
