apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-pong-ukiu56yxd-0-0-2
  namespace: default
spec:
  chart:
    spec:
      chart: pong
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: chart-repo
        namespace: default
      version: 0.2.0
  interval: 5m0s
  postRenderers:
  - kustomize:
      patches:
      - patch: "\napiVersion: apps/v1\nkind: (Deployment|ReplicaSet|StatefulSet|DaemonSet)\n\
          metadata:\n  name: will-be-ingored\nspec:\n  template:\n    metadata:\n\
          \      annotations:\n        dzsi.com/dzsx-network-function-href: https://10.157.102.82:8008/tmf-api/mano/serviceInventory/v4/default/service/service:DZSXNetworkFunction:default:cfb3df8f-f2ea-4a25-bd8c-e2ae83a80ede\n\
          \        dzsi.com/dzsx-network-function-id: service:DZSXNetworkFunction:default:cfb3df8f-f2ea-4a25-bd8c-e2ae83a80ede\n"
        target:
          kind: (Deployment|ReplicaSet|StatefulSet|DaemonSet)
  releaseName: de-com-pong-ukiu56yxd-0-0-2
  targetNamespace: default
  values: {}
