apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-3-pong-kvza3dubr-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 6a2c4286-2848-436f-8616-83fb94d3b85a
    image:
      imagePullSecrets: []
      pullPolicy: IfNotPresent
      repository: rt.cloud.dzsi.local/docker/rw.pong
      tag: '2005'
    macvlanNetName: mynad2
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    service:
      type: NodePort
