apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-ping-wnsx3yg3v-0-0-0
  namespace: default
spec:
  chart:
    spec:
      chart: ping
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pzkdisquiet
        namespace: default
      version: 0.3.0
  interval: 5m0s
  postRenderers:
  - kustomize:
      patches:
      - patch: "\napiVersion: apps/v1\nkind: (Deployment|ReplicaSet|StatefulSet|DaemonSet)\n\
          metadata:\n  name: will-be-ingored\nspec:\n  template:\n    metadata:\n\
          \      annotations:\n        dzsi.com/dzsx-network-function-href: https://10.157.102.73:8008/tmf-api/mano/serviceInventory/v4/default/service/service:DZSXNetworkFunction:default:8b03fd94-1854-49db-8e11-0397604cb730\n\
          \        dzsi.com/dzsx-network-function-id: service:DZSXNetworkFunction:default:8b03fd94-1854-49db-8e11-0397604cb730\n"
        target:
          kind: (Deployment|ReplicaSet|StatefulSet|DaemonSet)
  releaseName: de-com-ping-wnsx3yg3v-0-0-0
  targetNamespace: default
  values: {}
