apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-ping-wnsx3yg3v-0-0-0
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: f1ad2696-fe33-444a-8885-ec5608d30aa3
    macvlanNetName: mynad2
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/ping/metrics
        port: 18888
        scrape: true
      enabled: true
    replicaCount: '1'
    service:
      type: NodePort
