apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: he-com-ping-nudwokrmr-0-0-0
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 3d8ec73d-67bc-4842-8f34-5540730c7c9a
    macvlanNetName: mynad2
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/ping/metrics
        port: 18888
        scrape: true
      enabled: true
    replicaCount: '1'
    service:
      type: NodePort
