apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: he-36-ping-d8ug8yh9b-0-0-0
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 951b9b78-8c25-4fb0-b030-c1fcb5c439fb
    image:
      imagePullSecrets: []
      pullPolicy: IfNotPresent
      repository: rt.cloud.dzsi.local/docker/rw.ping
      tag: '2004'
    macvlanNetName: mynad2
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/ping/metrics
        port: 18888
        scrape: true
      enabled: true
    replicaCount: 1
    service:
      type: NodePort
