apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-89-pong-sdmezrt2z-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 376f2da8-de28-41c2-a908-fb0f174b1d5b
    image:
      imagePullSecrets: []
      pullPolicy: IfNotPresent
      repository: rt.cloud.dzsi.local/docker/rw.pong
      tag: '2005'
    macvlanNetName: mynad2
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    service:
      type: NodePort
