apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-pong-gcigwrtnl-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 0213b1ed-4e14-4144-b9a4-0fc8e21fcbf8
    image:
      imagePullSecrets: []
      pullPolicy: IfNotPresent
      repository: rt.cloud.dzsi.local/docker/rw.pong
      tag: '2005'
    macvlanNetName: defaultcombined3macvlanlinkprofile
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    service:
      type: NodePort
