apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-pong-gcigwrtnl-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 8f2708c7-a774-4c7d-bc16-e75651a30e54
    macvlanNetName: defaultcombined3macvlanlinkprofile
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    replicaCount: '2'
    service:
      type: NodePort
