apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-pong-gcigwrtnl-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 6f547427-f78f-445d-9a8b-ef32fb2b9e2a
    macvlanNetName: defaultcombined3macvlanlinkprofile
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    replicaCount: '2'
    service:
      type: NodePort
