apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-pong-gcigwrtnl-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: autobot-test25-pzk
      nsId: a79f8c1d-d063-4e11-8469-6404cb59499a
    macvlanNetName: defaultcombined3macvlanlinkprofile
    macvlanNetNamespace: default
    replicaCount: '2'
