apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-pong-8vsdmwiq3-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: autobot-test25-pzk
      nsId: 3eddbf19-d785-4d98-ac8c-e9afd2242b47
    macvlanNetName: defaultcombined4macvlanlinkprofile
    macvlanNetNamespace: default
    replicaCount: '2'
