apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-pong-y9rlrbgjw-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 2c16f916-2231-482d-ad5f-42b1ccf5a491
    macvlanNetName: defaultcombined2macvlanlinkprofile
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    replicaCount: '2'
    service:
      type: NodePort
