apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-45-pong-ehqakze5d-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 1bf81580-c46b-41ff-ab6a-14965e53892b
    macvlanNetName: mynad2
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    replicaCount: '1'
    service:
      type: NodePort
