apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-45-pong-ehqakze5d-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 2d71afb9-ab37-4f57-8df6-f01992117a0d
    macvlanNetName: mynad2
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    replicaCount: '1'
    service:
      type: NodePort
