apiVersion: v1
kind: Secret
metadata:
    name: fluxcdchartrepo3-secret
    namespace: default
stringData:
    password: ENC[AES256_GCM,data:9XgF,iv:ZPRYQzAEksNuJCAXPc144RXCcUq+aja8IpL2lUdzlGM=,tag:RlBG4PvCmUa9Vs+wlcsxyw==,type:str]
    username: ENC[AES256_GCM,data:ecMgUpcQXaN1CGGn,iv:gzzBCANXXrghl2lF6dqQ+wz3cMkNSjWCYwYFaZgUMM0=,tag:NvwArNBBHjcBw4GJlyv6Sw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mg59q8q78uz5cc6zn7qusevevrlmk43nc5q8q78tcq3q8qp45yvqnvq3lh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRlE5NDQ2REN0bVhqSHp6
            OE9nTVFjQWduYTlZd2M5MnlHS3gveVlGWXhFCmZzUlFWOTVPRFNVbmFkS0oxU3ZU
            V0IwM1JGTDJzRUtoZzhYSzA0bmUvSG8KLS0tIDJUdjNwam5UQm41V3U0Q0dUR2xH
            dWYxLzk0cjEwaW16ZGxiRUVrMnVGTUUKZQK9qyKwDWSA47X37Fb/3wTExK6+Ygw5
            9FcNGeDa2c7+nQPdnDytdjMXBv6FH+hD2DnnQh8sbANnlXAEzmDFTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T05:07:59Z"
    mac: ENC[AES256_GCM,data:YKbDb0nD1FxnifyaqpYjhfPjq7wm4azbWlKu91LlYClZk+T0LznMsgOFRUdpOGikVZ/fkS+ctUGhy7p3sxns1aPwHBsnMFlFSrEusXQSf4vOiGQlnqe8bu2L5X6kT7mjgyuxlNDsHu65CYTX//8uVf9+XFINP3E/Xi9LNh31esw=,iv:iUwAxu7GbElqHcK8HuFyC4o20ghwLvFRzwZ58gJJdDU=,tag:NdMcfYXOdhOsoK0aKvWoWQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
